#!/bin/sh
touch lastevents
LAST=`tail -n 1 lastevents | cut -d "|" -f 1`
if [ x$LAST = x ]; then
	LAST=0
fi

LAST=$(($LAST + 1))
TS=`date +%s`
# event number|timestamp|type|x|y|z
#                        type project repository arch
echo "$LAST|$TS|$1|$2|$3|$4" >> lastevents
