#!/bin/bash
ORIG=$PWD
export API=$1
export OBSPROJECT=$2
OUTDIR=$3
export REPONAME=$4
IFS=: read -ra SCHEDULERS <<< $5 # : seperated list of architectures in $5

[[ -d obs-repos/$OUTDIR ]] && {
    echo "obs-repos/$OUTDIR exists already. Looks like you already fetched this release from OBS"
    echo 'remove the obs-repos/*$RELEASE directories manually if you need to re-fetch'
    exit 1
}
mkdir -p obs-repos/$OUTDIR/$REPONAME
cd obs-repos/$OUTDIR/$REPONAME

export scheduler
for scheduler in "${SCHEDULERS[@]}"; do
	mkdir -p $scheduler
	cd $scheduler
	wget -N -c -r -nd -nH $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=cache
	wget -N -c -r -nd -nH $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=names
	wget -N -c -r -nd -nH $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=binaryversions
	wget -N -c -r -nd -nH $API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?view=solvstate
	# Grab 
	python $ORIG/tools/printbinaries.py "_repository?view=names" | xargs -L1 -Ixxx bash -c 'curl "$API/build/$OBSPROJECT/$REPONAME/$scheduler/_repository?xxx" \| cpio -idvm'
	cd ..
done
