#!/bin/sh
ORIG=$PWD
REPO=$1
PACKAGE=$2
API=$3
mkdir -p gitrepos/$PACKAGE
cd gitrepos/$PACKAGE
git init .
wget --no-check-certificate -nd -nH -cr $API/source/$REPO/$PACKAGE/_meta $API/source/$REPO/$PACKAGE/_attribute $API/source/$REPO/$PACKAGE/ 
#$API/source/$REPO/$x?expand=1
mv index.html _index
python $ORIG/tools/downloadfiles.py _index $API $REPO | sh
rm -f _index
git add .
git commit -s -m "Initial import"
cd ..
mv $PACKAGE $PACKAGE-import
git clone --mirror -n $PACKAGE-import $PACKAGE
cd $PACKAGE
git update-server-info
cd ..
rm -rf $PACKAGE-import
